# This is a basic workflow to help you get started with Actions

name: Update i18n

# Controls when the action will run. 
on: 
  push:
    branches: 
      - i18n-action-1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Set Branch 
        run: printf "UPDATE_BRANCH=i18n-updates-${GITHUB_RUN_NUMBER}" | tee --append "$GITHUB_ENV"
          
      - name: Checkout submodule & Commit changes
        run: |
          git checkout -b $UPDATE_BRANCH
          git submodule update --init --recursive --remote 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'chore: updating i18n submodule'
          git diff main --quiet || git push -u origin $UPDATE_BRANCH
