# This is a basic workflow to help you get started with Actions

name: Update i18n

# Controls when the action will run. 
on: 

  push:
    branches: 
      - i18n-action-1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Set Branch 
        run: printf "UPDATE_BRANCH=i18n-updates-${GITHUB_RUN_NUMBER}" | tee --append "$GITHUB_ENV"
      
      - name: Creating branch ${{ env.UPDATE_BRANCH }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.UPDATE_BRANCH }}
        #uses: peterjgrainger/action-create-branch@v2.0.1
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
        #  branch: ${{ env.UPDATE_BRANCH }}

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote
        
      #- name: Commit & Push changes
      #  uses: actions-js/push@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ env.UPDATE_BRANCH }}
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: updating i18n submodule"
          git push
